//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizSharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizSharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerGeography {
            get {
                object obj = ResourceManager.GetObject("answerGeography", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerGeographyCORRECT {
            get {
                object obj = ResourceManager.GetObject("answerGeographyCORRECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerGeographyWRONG {
            get {
                object obj = ResourceManager.GetObject("answerGeographyWRONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerHistory {
            get {
                object obj = ResourceManager.GetObject("answerHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerHistoryCORRECT {
            get {
                object obj = ResourceManager.GetObject("answerHistoryCORRECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerHistoryWRONG {
            get {
                object obj = ResourceManager.GetObject("answerHistoryWRONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerScience {
            get {
                object obj = ResourceManager.GetObject("answerScience", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerScienceCORRECT {
            get {
                object obj = ResourceManager.GetObject("answerScienceCORRECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerScienceWRONG {
            get {
                object obj = ResourceManager.GetObject("answerScienceWRONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerShowbiz {
            get {
                object obj = ResourceManager.GetObject("answerShowbiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerShowbizCORRECT {
            get {
                object obj = ResourceManager.GetObject("answerShowbizCORRECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerShowbizWRONG {
            get {
                object obj = ResourceManager.GetObject("answerShowbizWRONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerSports {
            get {
                object obj = ResourceManager.GetObject("answerSports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerSportsCORRECT {
            get {
                object obj = ResourceManager.GetObject("answerSportsCORRECT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap answerSportsWRONG {
            get {
                object obj = ResourceManager.GetObject("answerSportsWRONG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow_right {
            get {
                object obj = ResourceManager.GetObject("Arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background {
            get {
                object obj = ResourceManager.GetObject("background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_Exit {
            get {
                object obj = ResourceManager.GetObject("btn_Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_Exit_hover {
            get {
                object obj = ResourceManager.GetObject("btn_Exit_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_GeographyHOVER {
            get {
                object obj = ResourceManager.GetObject("btn_GeographyHOVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_GeographyMOUSEDOWN {
            get {
                object obj = ResourceManager.GetObject("btn_GeographyMOUSEDOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_HistoryHOVER {
            get {
                object obj = ResourceManager.GetObject("btn_HistoryHOVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_HistoryMOUSEDOWN {
            get {
                object obj = ResourceManager.GetObject("btn_HistoryMOUSEDOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_HowToPlay {
            get {
                object obj = ResourceManager.GetObject("btn_HowToPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_HowToPlay_hover {
            get {
                object obj = ResourceManager.GetObject("btn_HowToPlay_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_NewGame {
            get {
                object obj = ResourceManager.GetObject("btn_NewGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_NewGame_hover {
            get {
                object obj = ResourceManager.GetObject("btn_NewGame_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_ScienceHOVER {
            get {
                object obj = ResourceManager.GetObject("btn_ScienceHOVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_ScienceMOUSEDOWN {
            get {
                object obj = ResourceManager.GetObject("btn_ScienceMOUSEDOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_ShowbizHOVER {
            get {
                object obj = ResourceManager.GetObject("btn_ShowbizHOVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_ShowbizMOUSEDOWN {
            get {
                object obj = ResourceManager.GetObject("btn_ShowbizMOUSEDOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_SportsHOVER {
            get {
                object obj = ResourceManager.GetObject("btn_SportsHOVER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btn_SportsMOUSEDOWN {
            get {
                object obj = ResourceManager.GetObject("btn_SportsMOUSEDOWN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap categoryGeography {
            get {
                object obj = ResourceManager.GetObject("categoryGeography", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap categoryHistory {
            get {
                object obj = ResourceManager.GetObject("categoryHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap categoryScience {
            get {
                object obj = ResourceManager.GetObject("categoryScience", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap categoryShowbiz {
            get {
                object obj = ResourceManager.GetObject("categoryShowbiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap categorySports {
            get {
                object obj = ResourceManager.GetObject("categorySports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap curved_line_brush_by_mysteriofthekaulitz_d32aumc {
            get {
                object obj = ResourceManager.GetObject("curved_line_brush_by_mysteriofthekaulitz_d32aumc", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap curvevertical {
            get {
                object obj = ResourceManager.GetObject("curvevertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap curvevertical1 {
            get {
                object obj = ResourceManager.GetObject("curvevertical1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dfgdfs {
            get {
                object obj = ResourceManager.GetObject("dfgdfs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Form1_bgimg {
            get {
                object obj = ResourceManager.GetObject("Form1_bgimg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which country is the Albert canal?
        ///In which country is the Great Sandy Desert?
        ///In which city is the Prado art gallery?
        ///Where would you find the whispering gallery?
        ///What is the more common name for the collegiate church of St Peter in London?
        ///By what name is the Thames known as it passes through oxford?
        ///What is the capital of Madeira?
        ///On the bank of which river does the Portuguese capital of Lisbon stand?
        ///What is the capital of Pakistan?
        ///Which is the only us state named after an English county?
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Geography {
            get {
                return ResourceManager.GetString("Geography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgium
        ///Denmark
        ///Sri Lanka
        ///Sweden
        ///Australia
        ///Oceania
        ///South Africa
        ///Dubai
        ///Madrid
        ///Barcelona
        ///Sevilla
        ///Monaco
        ///St Paul&apos;s Cathedral
        ///Notre Dam
        ///St. Mary the Virgin
        ///St. ALbert
        ///Westminster Abbey
        ///Downton Abbey
        ///London
        ///Basilica of the Rose
        ///The Isis
        ///Shiits
        ///Sunits
        ///All answers
        ///Funchal
        ///Galapagos
        ///Oceania
        ///Drimor
        ///The Tagus
        ///Don
        ///Abu Dhabi
        ///Elisa
        ///Islamabad
        ///Baghdad
        ///Jordan
        ///Sri Lanka
        ///New Hampshire
        ///New York
        ///New Delhi
        ///Boston
        ///Luxembourg
        ///Belgium
        ///Netherlands
        ///Lichtenstain
        ///Vietnam
        ///Laos
        ///Cuba
        ///Costari [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Geography_answers {
            get {
                return ResourceManager.GetString("Geography_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferdinand Magellan
        ///Amerigo Vespuci
        ///John Kennedy
        ///Napoleon
        ///The Venerable Bede
        ///Vendetta
        ///Joan of Arc
        ///Jack the Ripper
        ///Cholera
        ///The Black Death
        ///The White Death
        ///Syphilis
        ///Jack the Ripper
        ///Sweeney Tod
        ///Charles Manson
        ///No one
        ///1929
        ///1927
        ///1945
        ///1912
        ///The Crimean
        ///The Austro-Russian
        ///The Italian
        ///The Soviet
        ///Rouen
        ///Nantes
        ///Paris
        ///Monaco
        ///Queen Victoria
        ///Anne Boleyn
        ///Queen Mary Margaret
        ///Queen Elizabeth I
        ///Fourteenth
        ///Sixteenth
        ///Thirteenth
        ///Tenth
        ///Jesse James
        ///John Mccuclkin
        ///Charles Montgomery
        ///Jimmy Jones        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string history_answers {
            get {
                return ResourceManager.GetString("history_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which Portuguese-born navigator was the first European to cross the Pacific Ocean?
        ///Which historical figure is widely regarded as the greatest of all the Anglo-Saxon scholars?
        ///What disease killed thousands of people in Glasgow in 1832?
        ///Which killer was also known as &apos;The Whitechapel Murderer&apos;?
        ///In which year was the Wall Street Crash?
        ///The Battle of Balaclava is a famous battle in which war?
        ///In which French city was Joan of Arc put to death?
        ///Who was the last British monarch of the House of Hanover?
        ///In  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string History_txt {
            get {
                return ResourceManager.GetString("History_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home_button {
            get {
                object obj = ResourceManager.GetObject("home_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap howtoplay_bg {
            get {
                object obj = ResourceManager.GetObject("howtoplay_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_Spin {
            get {
                object obj = ResourceManager.GetObject("img_Spin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo1 {
            get {
                object obj = ResourceManager.GetObject("logo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logobg {
            get {
                object obj = ResourceManager.GetObject("logobg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logobg_hover {
            get {
                object obj = ResourceManager.GetObject("logobg_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pickacategory {
            get {
                object obj = ResourceManager.GetObject("pickacategory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionGeography {
            get {
                object obj = ResourceManager.GetObject("questionGeography", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionHistory {
            get {
                object obj = ResourceManager.GetObject("questionHistory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionScience {
            get {
                object obj = ResourceManager.GetObject("questionScience", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionShowbiz {
            get {
                object obj = ResourceManager.GetObject("questionShowbiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap questionSports {
            get {
                object obj = ResourceManager.GetObject("questionSports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brass gets discoloured in air because of the presence of which of the following gases in air?
        ///Which of the following is a non metal that remains liquid at room temperature?
        ///Chlorophyll is a naturally occurring chelate compound in which central metal is
        ///Which of the following is used in pencils?
        ///Which of the following metals forms an amalgam with other metals?
        ///Chemical formula for water is
        ///The gas usually filled in the electric bulb is
        ///Washing soda is the common name for
        ///Quartz crystals normally used [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string science {
            get {
                return ResourceManager.GetString("science", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrogen sulphide
        ///Oxygen
        ///Carbon dioxide
        ///Nitrogen
        ///Bromine
        ///Phosphorous
        ///Chlorine
        ///Helium
        ///magnesium
        ///copper
        ///iron
        ///calcium
        ///Graphite
        ///Silicon
        ///Charcoal
        ///Phosphorous
        ///Mercury
        ///Lead
        ///Zinc
        ///Tin
        ///H2O
        ///Al2O3
        ///CaSiO3
        ///NaAlO2
        ///nitrogen
        ///hydrogen
        ///carbon dioxide
        ///oxygen
        ///Sodium carbonate
        ///Calcium bicarbonate
        ///Sodium bicarbonate
        ///Calcium carbonate
        ///silicon dioxide
        ///germanium oxide
        ///a mixture of germanium oxide and silicon dioxide
        ///sodium silicate
        ///Hydrogen
        ///Methane
        ///Nitrous oxide
        ///Carbon dioxide
        ///red liquid
        ///colo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string science_answers {
            get {
                return ResourceManager.GetString("science_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where did Pablo Escobar live?
        ///Where is the band Scorpions from?
        ///Madonna was a member of what band?
        ///Which &quot;How I Met Your Mother&quot; character says &quot;Wait for it&quot;?
        ///Which is Madonna&apos;s first single of all time?
        ///Which of these films didn&apos;t include Johnny Depp in its cast?
        ///What is Johnny Depp&apos;s middle name?
        ///Which song belongs to The Beatles? 	
        ///Who kissed Britney Spears and Christina Aguilera on stage in the MTV Video Music Awards of 2003?
        ///How many Oscars has Britney Spears won so far?
        ///Which singer has a ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string showbiz {
            get {
                return ResourceManager.GetString("showbiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia
        ///Spain
        ///Ecuador
        ///Argentina
        ///Germany
        ///United States
        ///Ireland
        ///United Kingdom
        ///Breakfast Club
        ///Madonna&apos;s band
        ///Virgin Girl
        ///Lonely Cools
        ///Barney Stinson
        ///Robin Scherbatsky
        ///Ted Mosby
        ///Bruce Wayne
        ///Everybody
        ///Holiday
        ///Lucky Star
        ///Like A Virgin
        ///Silence of the Lambs
        ///Finding Neverland
        ///Charlie and the Chocolate Factory
        ///The Tourist
        ///Christopher
        ///Dean
        ///Lee
        ///Allen
        ///Eight Days a Week
        ///Unchained Melody
        ///You Are Not Alone
        ///Hotel California
        ///Madonna
        ///Snoop Dogg
        ///Justin Timberlake
        ///Tony Bennett
        ///0
        ///1
        ///2
        ///5
        ///M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string showbiz_answers {
            get {
                return ResourceManager.GetString("showbiz_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is the only country to have played in each and every World Cup?
        ///In a game of poker, if you have 5 cards of the same suit, what is it called?
        ///In which sport may you shoot a free throw if you get fouled?
        ///What is another name for ping pong?
        ///Which sport involves goals, cleats and shin guards?
        ///Who won the men&apos;s singles Wimbledon title in 2011 and 2014?
        ///Who won the UEFA European Championship of 2000?
        ///Who won Wimbledon in 2014?
        ///Who won the 2014 world cup in football (soccer)?
        ///Who won the 2012 Champi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sports {
            get {
                return ResourceManager.GetString("sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil
        ///Germany
        ///Italy
        ///Greece
        ///Flush
        ///Full House
        ///Straight
        ///Five Of A Kind
        ///Basketball
        ///Hockey
        ///Volleyball
        ///Baseball
        ///Table Tennis
        ///Ball Bounce
        ///Mini Tennis
        ///None of these
        ///Soccer
        ///Football
        ///Track And Field
        ///Basketball
        ///Novak Djokovic
        ///Rafael Nadal
        ///Andy Roddick
        ///Andy Murray
        ///France
        ///Spain
        ///Italy
        ///Portugal
        ///Novak Djokovic
        ///Rafael Nadal
        ///Marin Cilic
        ///Roger Federer
        ///Germany
        ///Brazil
        ///The Netherlands
        ///Spain
        ///Chelsea
        ///Arsenal
        ///Everton
        ///Barcelona
        ///Spain
        ///Brazil
        ///Mexico
        ///United States
        ///Nike
        ///Puma
        ///Under Armor
        ///Ad [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sports_answers {
            get {
                return ResourceManager.GetString("sports_answers", resourceCulture);
            }
        }
    }
}
